In [2]:
import torch
x=torch.empty(2,3)
y=torch.empty(1)
print(x)
print(y)

tensor([[-9.1335e-20,  4.4103e-41, -9.2880e-20],
        [ 4.4103e-41, -9.3221e-20,  4.4103e-41]])
tensor([3.3631e-44])


In [ ]:
x=torch.rand(2,2)
print(x)

tensor([[0.9452, 0.6094],
        [0.8013, 0.5998]])


In [ ]:
x=torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
x=torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
z=torch.add(x,y)
print(z)

tensor([[0.7015, 0.3662],
        [0.3814, 0.5757]])
tensor([[0.1426, 0.3403],
        [0.8777, 0.5430]])
tensor([[0.8441, 0.7065],
        [1.2592, 1.1187]])


In [ ]:
y.add_(x)
print(y)

tensor([[0.8441, 0.7065],
        [1.2592, 1.1187]])


In [ ]:
z=torch.mul(x,y)
print(z)

tensor([[0.5922, 0.2587],
        [0.4803, 0.6440]])


In [ ]:
z=torch.div(x,y)
print(z)

tensor([[0.8311, 0.5183],
        [0.3029, 0.5146]])


In [ ]:
x=torch.rand(5,3)
print(x)
print(x[:,1])
print(x[1,:])
print(x[1,1])
print(x[1,1].item())


tensor([[0.3316, 0.5690, 0.8280],
        [0.9705, 0.6709, 0.8553],
        [0.6983, 0.8315, 0.1030],
        [0.7245, 0.5145, 0.5433],
        [0.5040, 0.8800, 0.1460]])
tensor([0.5690, 0.6709, 0.8315, 0.5145, 0.8800])
tensor([0.9705, 0.6709, 0.8553])
tensor(0.6709)
0.6708635091781616


In [ ]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)


tensor([[0.8300, 0.9868, 0.9648, 0.3552],
        [0.3346, 0.4028, 0.7644, 0.6897],
        [0.8095, 0.8975, 0.9633, 0.6805],
        [0.0854, 0.3666, 0.1790, 0.8528]])
tensor([0.8300, 0.9868, 0.9648, 0.3552, 0.3346, 0.4028, 0.7644, 0.6897, 0.8095,
        0.8975, 0.9633, 0.6805, 0.0854, 0.3666, 0.1790, 0.8528])


In [ ]:
y=x.view(-1,8)
print(y)
print(y.size())

tensor([[0.8300, 0.9868, 0.9648, 0.3552, 0.3346, 0.4028, 0.7644, 0.6897],
        [0.8095, 0.8975, 0.9633, 0.6805, 0.0854, 0.3666, 0.1790, 0.8528]])
torch.Size([2, 8])


In [1]:
import torch

# Create a 2D tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(tensor)
print(tensor.shape)

# Reshape the tensor to 1D
reshaped_tensor = tensor.view(3,2)
print("\nReshaped Tensor:")
print(reshaped_tensor)
print(reshaped_tensor.shape)

print(tensor.shape)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])

Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
torch.Size([2, 3])


In [2]:

x = torch.tensor([[1], [2]])


y = torch.tensor([[3, 4, 5]])


result = x + y
print("\nBroadcasting Result:")
print(result)



Broadcasting Result:
tensor([[4, 5, 6],
        [5, 6, 7]])


In [3]:

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped = x.view(3, 2)
print("\nReshaped Tensor:")
print(reshaped)

transposed = x.t()
print("\nTransposed Tensor (3x2 -> 2x3):")
print(transposed)



Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Transposed Tensor (3x2 -> 2x3):
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
import numpy as np

In [ ]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Gradient

In [ ]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
print(x)
y=x+3
print(y)
z=y*y*2
print(z)
#z=z.mean()
print(z)
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([1., 2., 3.], requires_grad=True)
tensor([4., 5., 6.], grad_fn=<AddBackward0>)
tensor([32., 50., 72.], grad_fn=<MulBackward0>)
tensor([32., 50., 72.], grad_fn=<MulBackward0>)
tensor([ 1.6000, 20.0000,  0.0240])


In [ ]:
x=torch.randn(3,requires_grad=True)
print(x)
x.requires_grad_(False)# to indicate the gradient is false
print(x)
y=x.detach()#to indicate the grad is false
print(y)
with torch.no_grad():
  z=x+2
  print(z)

tensor([-1.4856, -1.2744, -0.9325], requires_grad=True)
tensor([-1.4856, -1.2744, -0.9325])
tensor([-1.4856, -1.2744, -0.9325])
tensor([0.5144, 0.7256, 1.0675])


In [17]:
weights=torch.ones(4,requires_grad=True)
print(weights)
#print(weights)
for epoch in range(3):
  model_output=(weights*3).sum()
  model_output.backward()
  print(model_output)
  print(weights.grad)
  weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [ ]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0,requires_grad=True)
#forward pass and compute the loss
y_hat=w*x
loss=(y_hat-y)**2
print(loss)
#backward pass
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [ ]:
import numpy as np
x=np.array([1,2,3,4],dtype=np.float32)
y=np.array([2,4,6,8],dtype=np.float32)
w=0.0
#model prediction
def forward(x):
  return w*x
  #loss=MSE
def loss(y,y_predicted):
    return((y_predicted-y)**2).mean()
#gradient
#MSE=1/N *(w*x-y)
#dJ/dw=1/N 2x(w*x -y)
def gradient(x,y,y_predicted):
  return np.dot(2*x,y_predicted-y).mean()
print(f'prediction before training:f(5)={forward(5):.3f}')
n_iters=10
learning_rate=0.01
for epoch in range(n_iters):
  #prediction=forward pass
  y_pred=forward(x)
  #loss
  l=loss(y,y_pred)
  #gradient
  dw=gradient(x,y,y_pred)
  #updaate weights
  w-=learning_rate*dw
  if epoch%1==0:
    print(f'epoch{epoch+1}: w={w:.3f},loss={l:.8}')
    print(f'prediction after training:f(5)={forward(5):.3f}')


prediction before training:f(5)=0.000
epoch1: w=1.200,loss=30.0
prediction after training:f(5)=6.000
epoch2: w=1.680,loss=4.7999992
prediction after training:f(5)=8.400
epoch3: w=1.872,loss=0.76800019
prediction after training:f(5)=9.360
epoch4: w=1.949,loss=0.12288
prediction after training:f(5)=9.744
epoch5: w=1.980,loss=0.019660834
prediction after training:f(5)=9.898
epoch6: w=1.992,loss=0.0031457357
prediction after training:f(5)=9.959
epoch7: w=1.997,loss=0.00050330802
prediction after training:f(5)=9.984
epoch8: w=1.999,loss=8.0531863e-05
prediction after training:f(5)=9.993
epoch9: w=1.999,loss=1.2884395e-05
prediction after training:f(5)=9.997
epoch10: w=2.000,loss=2.0613531e-06
prediction after training:f(5)=9.999


In [ ]:
import torch
x=torch.tensor([1,2,3,4],dtype=torch.float32)
y=torch.tensor([2,4,6,8],dtype=torch.float32)
w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)
#model prediction
def forward(x):
  return w*x
  #loss=MSE
def loss(y,y_predicted):
    return((y_predicted-y)**2).mean()

n_iters=10
learning_rate=0.01
for epoch in range(n_iters):
  #prediction=forward pass
  y_pred=forward(x)
  #loss
  l=loss(y,y_pred)
  #gradient=backward pass
  l.backward()
  #updaate weights
  with torch.no_grad():
     w-=learning_rate * w.grad
  w.grad.zero_()
  if epoch%1==0:
    print(f'epoch{epoch+1}: w={w:.3f},loss={l:.8f}')
    print(f'prediction after training:f(5)={forward(5):.3f}')


epoch1: w=0.300,loss=30.00000000
prediction after training:f(5)=1.500
epoch2: w=0.555,loss=21.67499924
prediction after training:f(5)=2.775
epoch3: w=0.772,loss=15.66018772
prediction after training:f(5)=3.859
epoch4: w=0.956,loss=11.31448650
prediction after training:f(5)=4.780
epoch5: w=1.113,loss=8.17471695
prediction after training:f(5)=5.563
epoch6: w=1.246,loss=5.90623236
prediction after training:f(5)=6.229
epoch7: w=1.359,loss=4.26725292
prediction after training:f(5)=6.794
epoch8: w=1.455,loss=3.08308983
prediction after training:f(5)=7.275
epoch9: w=1.537,loss=2.22753215
prediction after training:f(5)=7.684
epoch10: w=1.606,loss=1.60939169
prediction after training:f(5)=8.031
